/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Controlador.MyList;
import Modelo.Analista;
import Modelo.Empleado;
import Modelo.Programador;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.JTextPane;

/**
 *
 * @author ConoMaster
 */
public class PanelVisualizarEmpleados extends javax.swing.JPanel {

    /**
     * Creates new form PanelVisualizarEmpleados
     */
    VistaPrincipal vistaPrincipal;
    
    public PanelVisualizarEmpleados(VistaPrincipal frame) {
        initComponents();
        this.vistaPrincipal = frame;
        
        mostrarDatos();
        editarTexto(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombreField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        sueldoField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        sueldoMaxField = new javax.swing.JTextField();
        labelSustitutivo1 = new javax.swing.JLabel();
        fieldSustitutivo1 = new javax.swing.JTextField();
        labelSustitutivo2 = new javax.swing.JLabel();
        fieldSustitutivo2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        fechaField = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        tipoField = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        numeroField = new javax.swing.JTextField();

        jLabel5.setText("Sueldo :");

        jLabel4.setText("Nombre :");

        labelSustitutivo1.setText("jLabel7");

        labelSustitutivo2.setText("jLabel8");

        jLabel9.setText("Fecha :");

        tipoField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jScrollPane6.setViewportView(tipoField);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Yu Gothic Medium", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Programa para la gestión de empleados");
        jLabel1.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel6.setText("Sueldo Max :");

        jLabel3.setText("Número :");

        numeroField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(312, 312, 312)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(nombreField, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(115, 115, 115))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(25, 25, 25)
                            .addComponent(sueldoField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(sueldoMaxField, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(fechaField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(56, 56, 56))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(149, 149, 149)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(numeroField, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fieldSustitutivo1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(131, 131, 131)
                        .addComponent(fieldSustitutivo2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelSustitutivo1)
                        .addGap(186, 186, 186)
                        .addComponent(labelSustitutivo2)))
                .addContainerGap(233, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numeroField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sueldoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(sueldoMaxField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSustitutivo1)
                    .addComponent(labelSustitutivo2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldSustitutivo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldSustitutivo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

public void mostrarDatos(){
    //AQUI ES DONDE CONTROLO LA ACTIVACIÓN O DESACTIVACIÓN DEL BOTON CALCULAR
    Empleado aux = (Empleado) vistaPrincipal.lista.getActualNode().getMain();
    vistaPrincipal.botones.getBotonCalcular().setEnabled(activarCalculo(aux));
    tipoField.setText(vistaPrincipal.lista.getActualNode().getMain().getClass().getSimpleName());
    numeroField.setText(""+aux.getNumero());
    nombreField.setText(aux.getNombre());
    sueldoField.setText(""+aux.getSueldo());
    sueldoMaxField.setText(""+aux.getSueldoMaximo());
    fechaField.setText(aux.getFechaAlta().toString());
    diferenciarTipo();
}

public void mostrarDatosPrimero(){
    vistaPrincipal.lista.goingFirstNode();
    Empleado aux = (Empleado) vistaPrincipal.lista.getFirstNode().getMain();
    vistaPrincipal.botones.getBotonCalcular().setEnabled(activarCalculo(aux));
    tipoField.setText(vistaPrincipal.lista.getActualNode().getMain().getClass().getSimpleName());
    numeroField.setText(""+aux.getNumero());
    nombreField.setText(aux.getNombre());
    sueldoField.setText(""+aux.getSueldo());
    sueldoMaxField.setText(""+aux.getSueldoMaximo());
    fechaField.setText(aux.getFechaAlta().toString());
    diferenciarTipo();
   // activarDesactivarBotonesAtras(false);
}
public void mostrarDatosVacios(){
    
    tipoField.setText("");
    numeroField.setText("");
    nombreField.setText("");
    sueldoField.setText("");
    sueldoMaxField.setText("");
    fechaField.setText("");
    tipoField.setText("");
    labelSustitutivo1.setText("");
    labelSustitutivo2.setText("");
    fieldSustitutivo1.setText("");
    fieldSustitutivo2.setText("");
}

public void diferenciarTipo(){
    Empleado aux = (Empleado)vistaPrincipal.lista.getActualNode().getMain();
    //aux.getClass().getSimpleName().contains("Analista")
    if(aux instanceof Analista){
        Analista analista = (Analista)aux;
        labelSustitutivo1.setText("Plus anual");
        labelSustitutivo2.setText("Horas trabajadas");
        fieldSustitutivo1.setText("" + analista.getPlusAnual());
        fieldSustitutivo2.setText("" + analista.getHorasTrabajadas());
    }else{
        Programador programador = (Programador)aux;
        labelSustitutivo1.setText("Sueldo extra mensual");
        labelSustitutivo2.setText("Lenguaje programación favorita");
        fieldSustitutivo1.setText("" + programador.getSueldoExtraMensual());
        fieldSustitutivo2.setText(programador.getLenguajeFavorito());    
    }
}

public void editarTexto(boolean c){
    tipoField.setEditable(c);
    numeroField.setEditable(c);
    nombreField.setEditable(c);
    sueldoField.setEditable(c);
    sueldoMaxField.setEditable(c);
    fechaField.setEditable(c);
}

public boolean activarCalculo(Empleado a){
    
        if("Analista".equals(a.getClass().getSimpleName())){
            Analista aux = (Analista)a;
            if(aux.getSueldo() == aux.getSueldoMaximo()){
                return false;
            }
            if(aux.cumpleAnios()){
                return true;
            }else{
                return false;
            }
        }else{
            Programador aux = (Programador)a;
            if(aux.getSueldo() == aux.getSueldoMaximo()){
                return false;
            }
            if(aux.cumpleMes()){
                return true;
            }else{
                return false;
            }
        
}
}  

    public VistaPrincipal getVistaPrincipal() {
        return vistaPrincipal;
    }

    public void setVistaPrincipal(VistaPrincipal vistaPrincipal) {
        this.vistaPrincipal = vistaPrincipal;
    }

    public JTextField getFechaField() {
        return fechaField;
    }

    public void setFechaField(JTextField fechaField) {
        this.fechaField = fechaField;
    }

    public JTextField getFieldSustitutivo1() {
        return fieldSustitutivo1;
    }

    public void setFieldSustitutivo1(JTextField fieldSustitutivo1) {
        this.fieldSustitutivo1 = fieldSustitutivo1;
    }

    public JTextField getFieldSustitutivo2() {
        return fieldSustitutivo2;
    }

    public void setFieldSustitutivo2(JTextField fieldSustitutivo2) {
        this.fieldSustitutivo2 = fieldSustitutivo2;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public void setjLabel6(JLabel jLabel6) {
        this.jLabel6 = jLabel6;
    }

    public JLabel getjLabel9() {
        return jLabel9;
    }

    public void setjLabel9(JLabel jLabel9) {
        this.jLabel9 = jLabel9;
    }

    public JScrollPane getjScrollPane6() {
        return jScrollPane6;
    }

    public void setjScrollPane6(JScrollPane jScrollPane6) {
        this.jScrollPane6 = jScrollPane6;
    }

    public JLabel getLabelSustitutivo1() {
        return labelSustitutivo1;
    }

    public void setLabelSustitutivo1(JLabel labelSustitutivo1) {
        this.labelSustitutivo1 = labelSustitutivo1;
    }

    public JLabel getLabelSustitutivo2() {
        return labelSustitutivo2;
    }

    public void setLabelSustitutivo2(JLabel labelSustitutivo2) {
        this.labelSustitutivo2 = labelSustitutivo2;
    }

    public JTextField getNombreField() {
        return nombreField;
    }

    public void setNombreField(JTextField nombreField) {
        this.nombreField = nombreField;
    }

    public JTextField getNumeroField() {
        return numeroField;
    }

    public void setNumeroField(JTextField numeroField) {
        this.numeroField = numeroField;
    }

    public JTextField getSueldoField() {
        return sueldoField;
    }

    public void setSueldoField(JTextField sueldoField) {
        this.sueldoField = sueldoField;
    }

    public JTextField getSueldoMaxField() {
        return sueldoMaxField;
    }

    public void setSueldoMaxField(JTextField sueldoMaxField) {
        this.sueldoMaxField = sueldoMaxField;
    }

    public JTextPane getTipoField() {
        return tipoField;
    }

    public void setTipoField(JTextPane tipoField) {
        this.tipoField = tipoField;
    }


    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fechaField;
    private javax.swing.JTextField fieldSustitutivo1;
    private javax.swing.JTextField fieldSustitutivo2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel labelSustitutivo1;
    private javax.swing.JLabel labelSustitutivo2;
    private javax.swing.JTextField nombreField;
    private javax.swing.JTextField numeroField;
    private javax.swing.JTextField sueldoField;
    private javax.swing.JTextField sueldoMaxField;
    private javax.swing.JTextPane tipoField;
    // End of variables declaration//GEN-END:variables
}
