/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Controlador.MyList.Node;
import Modelo.Analista;
import Modelo.Empleado;
import Modelo.Programador;
import java.awt.BorderLayout;
import javax.swing.DefaultListModel;

/**
 *
 * @author ConoMaster
 */
public class PanelJLista extends javax.swing.JPanel {

    /**
     * Creates new form PanelJLista
     */
    VistaPrincipal vistaPrincipal;
    public PanelJLista(VistaPrincipal frame) {
        initComponents();
        vistaPrincipal = frame;   
        jList1.setModel(modeloLista());
        jScrollPane1.setViewportView(jList1);
    }
    
  
    
    private DefaultListModel modeloLista()
    {
        
        DefaultListModel<String> modelo = new DefaultListModel<>();
        Node temp = vistaPrincipal.lista.getFirstNode();
        while(temp != null){
            if (temp.getMain() instanceof Empleado)
                {
                    
                    String infoObjeto = "Información del objeto: " + temp.getMain().toString();
                    modelo.addElement(infoObjeto);  

                }
                
            else
                modelo.addElement("No hay elementos");
            
            temp = temp.getNextNode();
        }
        
        
        return modelo;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        botonAtras = new javax.swing.JButton();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        botonAtras.setText("jButton1");
        botonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
                .addComponent(botonAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtrasActionPerformed
        
        
        vistaPrincipal.botones.setVisible(true);
        vistaPrincipal.panelEmpleados.setVisible(true);
        vistaPrincipal.add(vistaPrincipal.panelEmpleados, BorderLayout.SOUTH);
        vistaPrincipal.add(vistaPrincipal.botones, BorderLayout.SOUTH);
        vistaPrincipal.panelJList.setVisible(false);
        
    }//GEN-LAST:event_botonAtrasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAtras;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
