/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.MyList;
import Controlador.MyList.Node;
import Modelo.Analista;
import Modelo.ESaldoNoValido;
import Modelo.Empleado;
import Modelo.Fecha;
import Modelo.Programador;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GridLayout;
import java.awt.List;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collection;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ConoMaster
 */
public class VistaPrincipal extends javax.swing.JFrame {

    MyList lista = new MyList();
    PanelBotones botones;
    PanelVisualizarEmpleados panelEmpleados;
    PanelCreacionEmpleado crearEmpleados = new PanelCreacionEmpleado(this);
    PanelJLista panelJList;
    
    public VistaPrincipal() throws ESaldoNoValido  {
        añadirEmpleados();
        botones = new PanelBotones(this);
        panelEmpleados = new PanelVisualizarEmpleados(this);
        panelJList = new PanelJLista(this);
        initComponents();
        estructura();

        
        /*
        
        if(lista.getContador() == -1){
            mostrarDatosVacios();
            
            editarTexto(false);
        }else{
            botonAtras.setEnabled(false);
            botonPrimero.setEnabled(false);
            mostrarDatos();
            editarTexto(false);
            botonCargar.setEnabled(false);
        }
        
        botonAceptar.setVisible(false);
        botonCancelar.setVisible(false);
        */
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 656, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 576, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new VistaPrincipal().setVisible(true);
                } catch (ESaldoNoValido ex) {
                    Logger.getLogger(VistaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame jFrame1;
    // End of variables declaration//GEN-END:variables



/*
public void activarDesactivarBotonesSiguiente(boolean t){
    botonSiguiente.setEnabled(t);
    botonUltimo.setEnabled(t);
}
public void activarDesactivarBotonesAtras(boolean t){
    botonAtras.setEnabled(t);
    botonPrimero.setEnabled(t);
}
/*
public boolean comprobarFields(){
    
}

*/
public void estructura(){
    this.setResizable(false);
    this.setSize(1000,800);
    this.setLayout(new BorderLayout());
    this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    panelEmpleados.setSize(400,400);
    panelEmpleados.setBackground(Color.YELLOW);
    botones.setSize(1000,200);
    botones.setBackground(Color.red);
    this.getContentPane().add(panelEmpleados, BorderLayout.CENTER);
    this.getContentPane().add(botones,BorderLayout.SOUTH);
    
}


public void añadirEmpleados() throws ESaldoNoValido{
    lista.add(new Analista(15, 15, 1, "Pepe", 1000, 1500, new Fecha("9/2/1997")), 1);
    lista.add(new Analista(15, 15, 2, "Juan", 1000, 1500, new Fecha("9/11/1997")), 2);
   
   for(int i = 0; i <= 20; i++){
            int numero = (int) (Math.floor(Math.random() * (1000-2000+1)+2000));
            try {
                lista.add(new Programador(0,null,numero,"Empleado "+ i,0,1,new Fecha()), numero);
            } catch (ESaldoNoValido ex) {
                Logger.getLogger(PanelBotones.class.getName()).log(Level.SEVERE, null, ex.getMessage());
            }
        }
    
}

public void primerElemento(){
        lista.goingFirstNode();
        panelEmpleados.mostrarDatos();
        botones.activarDesactivarBotonesAtras(false);
        botones.activarDesactivarBotonesSiguiente(true);
}

public ArrayList generarArrayList(){
    ArrayList empleados = new ArrayList(); 
    Node aux = lista.getFirstNode();
    while(aux != null){
        empleados.add((Empleado)aux.getMain());
        aux = aux.getNextNode();
    }
        return empleados;
}
}
